import type { Motorcycle } from '@/lib/types';

export const motorcycles: Motorcycle[] = [
  {
    id: '1',
    make: 'Royal Enfield',
    model: 'Classic 350',
    year: 2021,
    price: 180000,
    mileage: 8500,
    condition: 'Excellent',
    description: 'A timeless classic with modern features. This Classic 350 is in pristine condition with low mileage, perfect for city commutes and highway cruising in Bihar.',
    images: [
      'https://picsum.photos/seed/re1/800/600',
      'https://picsum.photos/seed/re1a/800/600',
      'https://picsum.photos/seed/re1b/800/600',
    ],
  },
  {
    id: '2',
    make: 'Bajaj',
    model: 'Pulsar NS200',
    year: 2019,
    price: 110000,
    mileage: 15000,
    condition: 'Good',
    description: 'Experience the thrill of naked sport biking with the Pulsar NS200. Well-maintained and ready for a new owner to enjoy its performance on the streets of Muzaffarpur.',
    images: [
      'https://picsum.photos/seed/bajaj2/800/600',
      'https://picsum.photos/seed/bajaj2a/800/600',
      'https://picsum.photos/seed/bajaj2b/800/600',
    ],
  },
  {
    id: '3',
    make: 'TVS',
    model: 'Apache RTR 160 4V',
    year: 2022,
    price: 125000,
    mileage: 4200,
    condition: 'Excellent',
    description: 'The perfect blend of performance and style, this Apache RTR 160 4V is almost brand new with very low mileage. A great bike for young riders.',
    images: [
      'https://picsum.photos/seed/tvs3/800/600',
      'https://picsum.photos/seed/tvs3a/800/600',
      'https://picsum.photos/seed/tvs3b/800/600',
    ],
  },
  {
    id: '4',
    make: 'Hero',
    model: 'Splendor Plus',
    year: 2020,
    price: 65000,
    mileage: 22000,
    condition: 'Good',
    description: 'India\'s most trusted motorcycle. This Splendor Plus is a joy to ride, known for its incredible mileage and low maintenance costs. Perfect for daily use.',
    images: [
      'https://picsum.photos/seed/hero4/800/600',
      'https://picsum.photos/seed/hero4a/800/600',
      'https://picsum.photos/seed/hero4b/800/600',
    ],
  },
  {
    id: '5',
    make: 'Honda',
    model: 'CB Shine',
    year: 2018,
    price: 58000,
    mileage: 35000,
    condition: 'Fair',
    description: 'A reliable and comfortable commuter. This CB Shine has been a dependable companion and is looking for its next adventure. Shows some signs of wear but runs great.',
    images: [
      'https://picsum.photos/seed/honda5/800/600',
      'https://picsum.photos/seed/honda5a/800/600',
      'https://picsum.photos/seed/honda5b/800/600',
    ],
  },
  {
    id: '6',
    make: 'Royal Enfield',
    model: 'Himalayan',
    year: 2021,
    price: 210000,
    mileage: 11500,
    condition: 'Excellent',
    description: 'The ultimate adventure tourer for Indian roads. Ready for any terrain, this Himalayan comes with touring accessories. Meticulously maintained in Muzaffarpur.',
    images: [
      'https://picsum.photos/seed/re6/800/600',
      'https://picsum.photos/seed/re6a/800/600',
      'https://picsum.photos/seed/re6b/800/600',
    ],
  },
];
