import type { Motorcycle, Testimonial } from '@/lib/types';

export const motorcycles: Motorcycle[] = [
  {
    id: '1',
    make: 'Royal Enfield',
    model: 'Classic 350',
    year: 2020,
    price: 175000,
    kmDriven: 17580,
    engineDisplacement: 350,
    registration: 'BR 05',
    condition: 'Good',
    description: 'A well-maintained Royal Enfield Classic 350 from 2020. A reliable and stylish ride for the streets of Bihar.',
    images: [
      'https://picsum.photos/seed/re-classic/800/600',
      'https://picsum.photos/seed/re-classic-a/800/600',
      'https://picsum.photos/seed/re-classic-b/800/600',
    ],
  },
  {
    id: '2',
    make: 'Yamaha',
    model: 'R15',
    year: 2019,
    price: 140000,
    kmDriven: 19600,
    engineDisplacement: 155,
    registration: 'BR 05',
    condition: 'Good',
    description: 'A sporty Yamaha R15 from 2019. Perfect for those who love performance and style. Ready for a new owner in Muzaffarpur.',
    images: [
      'https://picsum.photos/seed/yamaha-r15/800/600',
      'https://picsum.photos/seed/yamaha-r15-a/800/600',
      'https://picsum.photos/seed/yamaha-r15-b/800/600',
    ],
  },
  {
    id: '3',
    make: 'Bajaj',
    model: 'N160',
    year: 2023,
    price: 130000,
    kmDriven: 12066,
    engineDisplacement: 160,
    registration: 'BR 05',
    condition: 'Excellent',
    description: 'A nearly new Bajaj N160 from 2023. Low KM driven and in excellent condition. Great value for a modern bike.',
    images: [
      'https://picsum.photos/seed/bajaj-n160/800/600',
      'https://picsum.photos/seed/bajaj-n160-a/800/600',
      'https://picsum.photos/seed/bajaj-n160-b/800/600',
    ],
  },
  {
    id: '4',
    make: 'Bajaj',
    model: 'NS160',
    year: 2020,
    price: 105000,
    kmDriven: 15666,
    engineDisplacement: 160,
    registration: 'BR 31',
    condition: 'Good',
    description: 'The powerful Bajaj NS160 from 2020. A great combination of power and agility. Has been kept in good condition.',
    images: [
      'https://picsum.photos/seed/bajaj-ns160/800/600',
      'https://picsum.photos/seed/bajaj-ns160-a/800/600',
      'https://picsum.photos/seed/bajaj-ns160-b/800/600',
    ],
  },
  {
    id: '5',
    make: 'Hero',
    model: 'Glamour',
    year: 2019,
    price: 75000,
    kmDriven: 18000,
    engineDisplacement: 125,
    registration: 'BR 06',
    condition: 'Good',
    description: 'A stylish and reliable Hero Glamour from 2019. Known for its solid performance and fuel efficiency.',
    images: [
      'https://picsum.photos/seed/hero-glamour/800/600',
      'https://picsum.photos/seed/hero-glamour-a/800/600',
      'https://picsum.photos/seed/hero-glamour-b/800/600',
    ],
  },
  {
    id: '6',
    make: 'Bajaj',
    model: 'Pulsar 125',
    year: 2019,
    price: 80000,
    kmDriven: 20222,
    engineDisplacement: 125,
    registration: 'BR 05',
    condition: 'Good',
    description: 'A 2019 Bajaj Pulsar 125, the perfect entry into the Pulsar family. Balances performance with everyday usability.',
    images: [
      'https://picsum.photos/seed/bajaj-pulsar/800/600',
      'https://picsum.photos/seed/bajaj-pulsar-a/800/600',
      'https://picsum.photos/seed/bajaj-pulsar-b/800/600',
    ],
  },
   {
    id: '7',
    make: 'Hero',
    model: 'Pleasure',
    year: 2020,
    price: 60000,
    kmDriven: 17855,
    engineDisplacement: 110,
    registration: 'BR 05',
    condition: 'Good',
    description: 'A 2020 Hero Pleasure scooter, perfect for city commuting. Easy to handle and very fuel-efficient.',
    images: [
      'https://picsum.photos/seed/hero-pleasure/800/600',
      'https://picsum.photos/seed/hero-pleasure-a/800/600',
      'https://picsum.photos/seed/hero-pleasure-b/800/600',
    ],
  },
   {
    id: '8',
    make: 'Royal Enfield',
    model: 'Hunter 350',
    year: 2023,
    price: 190000,
    kmDriven: 7852,
    engineDisplacement: 350,
    registration: 'BR 01',
    condition: 'Excellent',
    description: 'A modern and stylish 2023 Royal Enfield Hunter 350. Great for navigating city streets with ease.',
    images: [
      'https://picsum.photos/seed/re-hunter/800/600',
      'https://picsum.photos/seed/re-hunter-a/800/600',
      'https://picsum.photos/seed/re-hunter-b/800/600',
    ],
  },
   {
    id: '9',
    make: 'TVS',
    model: 'Apache RTR 200',
    year: 2021,
    price: 135000,
    kmDriven: 21055,
    engineDisplacement: 200,
    registration: 'BR 05',
    condition: 'Good',
    description: 'The thrilling TVS Apache RTR 200 from 2021. A performance machine that is sure to excite. Well-maintained.',
    images: [
      'https://picsum.photos/seed/tvs-apache/800/600',
      'https://picsum.photos/seed/tvs-apache-a/800/600',
      'https://picsum.photos/seed/tvs-apache-b/800/600',
    ],
  },
   {
    id: '10',
    make: 'Hero',
    model: 'Splendor',
    year: 2023,
    price: 70000,
    kmDriven: 3455,
    engineDisplacement: 110,
    registration: 'BR 06',
    condition: 'Excellent',
    description: 'A 2023 Hero Splendor with very low KM driven. The king of commuters, offering unmatched reliability and economy.',
    images: [
      'https://picsum.photos/seed/hero-splendor/800/600',
      'https://picsum.photos/seed/hero-splendor-a/800/600',
      'https://picsum.photos/seed/hero-splendor-b/800/600',
    ],
  },
];

export const testimonials: Testimonial[] = [
    {
      id: '1',
      name: 'Rohan Kumar',
      location: 'Muzaffarpur, Bihar',
      review: 'Excellent service and a fantastic bike! The team at Mota Bhai Automobiles made the whole process smooth and transparent. I couldn\'t be happier with my Royal Enfield.',
      rating: 5,
      image: 'https://picsum.photos/seed/rohan/100/100',
    },
    {
      id: '2',
      name: 'Priya Sharma',
      location: 'Patna, Bihar',
      review: 'I sold my old bike and got a great price for it. The home inspection was convenient, and I got paid instantly. Highly recommend Mota Bhai for selling your bike!',
      rating: 5,
      image: 'https://picsum.photos/seed/priya/100/100',
    },
    {
      id: '3',
      name: 'Amit Singh',
      location: 'Darbhanga, Bihar',
      review: 'Found a well-maintained Pulsar at a very reasonable price. The staff was helpful and answered all my questions. A trustworthy place for second-hand bikes.',
      rating: 4,
      image: 'https://picsum.photos/seed/amit/100/100',
    },
    {
      id: '4',
      name: 'Sneha Gupta',
      location: 'Muzaffarpur, Bihar',
      review: 'The process of buying my first scooter was so easy here. They have a good collection and the prices are fair. I\'m very satisfied with my purchase.',
      rating: 5,
      image: 'https://picsum.photos/seed/sneha/100/100',
    },
  ];
