import type { Motorcycle } from '@/lib/types';

export const motorcycles: Motorcycle[] = [
  {
    id: '1',
    make: 'Harley-Davidson',
    model: 'Iron 883',
    year: 2021,
    price: 9500,
    mileage: 3500,
    condition: 'Excellent',
    description: 'A sleek and powerful cruiser, perfect for city riding and weekend trips. This Iron 883 is in pristine condition with low mileage and custom exhaust.',
    images: [
      'https://picsum.photos/seed/moto1/800/600',
      'https://picsum.photos/seed/moto1a/800/600',
      'https://picsum.photos/seed/moto1b/800/600',
    ],
  },
  {
    id: '2',
    make: 'Honda',
    model: 'CBR600RR',
    year: 2019,
    price: 8200,
    mileage: 8000,
    condition: 'Good',
    description: 'Experience the thrill of the track with this agile and responsive sportbike. Well-maintained and ready for a new owner to enjoy its performance.',
    images: [
      'https://picsum.photos/seed/moto2/800/600',
      'https://picsum.photos/seed/moto2a/800/600',
      'https://picsum.photos/seed/moto2b/800/600',
    ],
  },
  {
    id: '3',
    make: 'Kawasaki',
    model: 'Ninja 400',
    year: 2022,
    price: 5500,
    mileage: 1200,
    condition: 'Excellent',
    description: 'The perfect entry-level sportbike, combining manageable power with aggressive styling. Almost brand new with very low mileage.',
    images: [
      'https://picsum.photos/seed/moto3/800/600',
      'https://picsum.photos/seed/moto3a/800/600',
      'https://picsum.photos/seed/moto3b/800/600',
    ],
  },
  {
    id: '4',
    make: 'Ducati',
    model: 'Monster 821',
    year: 2020,
    price: 11000,
    mileage: 5500,
    condition: 'Good',
    description: 'Iconic Italian design meets thrilling performance. This Monster 821 is a joy to ride, with a powerful engine and comfortable ergonomics.',
    images: [
      'https://picsum.photos/seed/moto4/800/600',
      'https://picsum.photos/seed/moto4a/800/600',
      'https://picsum.photos/seed/moto4b/800/600',
    ],
  },
  {
    id: '5',
    make: 'Royal Enfield',
    model: 'Classic 350',
    year: 2018,
    price: 3800,
    mileage: 15000,
    condition: 'Fair',
    description: 'A timeless classic with retro charm. This Classic 350 has been a reliable companion and is looking for its next adventure. Shows some signs of wear but runs great.',
    images: [
      'https://picsum.photos/seed/moto5/800/600',
      'https://picsum.photos/seed/moto5a/800/600',
      'https://picsum.photos/seed/moto5b/800/600',
    ],
  },
  {
    id: '6',
    make: 'BMW',
    model: 'R1250GS',
    year: 2021,
    price: 18500,
    mileage: 9500,
    condition: 'Excellent',
    description: 'The ultimate adventure bike. Ready for any terrain, this R1250GS comes fully loaded with all the touring packages. Meticulously maintained.',
    images: [
      'https://picsum.photos/seed/moto6/800/600',
      'https://picsum.photos/seed/moto6a/800/600',
      'https://picsum.photos/seed/moto6b/800/600',
    ],
  },
];
